repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uv run isort
        language: system
        args: ["--profile", "black"]
        files: ^(src/|tests/)
        types: [python]

      - id: black  
        name: black
        entry: uv run black
        language: system 
        args: ["--target-version", "py312"]
        files: ^(src/|tests/)
        types: [python]

      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        files: ^(src/|tests/)$
        types: [python]

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        files: ^(tests/)$
        pass_filenames: false
        always_run: true