name: Tests
on: [ push, pull_request ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python 3.8.20
        run: uv python install 3.8.20
      - name: Install dependencies (CPU only)
        run: uv sync --extra cpu --no-dev
      - name: Test with pytest
        run: uv run pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.20"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv tool install flake8
      - name: Run flake8
        run: uv tool run flake8 src/ tests/